#数据库的配置
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/booking?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  devtools:
    restart:
      enabled: true #开启热部署
  freemarker:
    cache: false #页面不加载缓存 修改及时生效
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

mybatis-plus:
  type-aliases-package: com.peanut.entity
  mapper-locations: classpath:mappers/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 9999
